
import java.awt.Window;
import java.text.DecimalFormat;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aodhan
 */
public class Deposit extends javax.swing.JFrame {

    DecimalFormat formatter = new DecimalFormat("#0.00");
    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        euro2 = new javax.swing.JButton();
        euro = new javax.swing.JButton();
        fifty = new javax.swing.JButton();
        twenty = new javax.swing.JButton();
        ten = new javax.swing.JButton();
        five = new javax.swing.JButton();
        sum = new javax.swing.JTextField();
        euro5 = new javax.swing.JButton();
        euro10 = new javax.swing.JButton();
        euro20 = new javax.swing.JButton();
        euro50 = new javax.swing.JButton();
        chargefield = new javax.swing.JTextField();
        charge = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        check = new javax.swing.JButton();
        finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        euro2.setText("2 EURO");
        euro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euro2ActionPerformed(evt);
            }
        });

        euro.setText("1 EURO");
        euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroActionPerformed(evt);
            }
        });

        fifty.setText("50 cent");
        fifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftyActionPerformed(evt);
            }
        });

        twenty.setText("20 cent");
        twenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyActionPerformed(evt);
            }
        });

        ten.setText("10 cent");
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });

        five.setText("5 cent");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        sum.setEditable(false);
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        euro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment/5.jpg"))); // NOI18N
        euro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euro5ActionPerformed(evt);
            }
        });

        euro10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment/10.jpg"))); // NOI18N
        euro10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euro10ActionPerformed(evt);
            }
        });

        euro20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20.jpg"))); // NOI18N
        euro20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euro20ActionPerformed(evt);
            }
        });

        euro50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/50.jpg"))); // NOI18N
        euro50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euro50ActionPerformed(evt);
            }
        });

        chargefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargefieldActionPerformed(evt);
            }
        });

        charge.setText("Charge Card");
        charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount to Charge to Card");

        check.setText("Check Balance");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(euro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fifty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(twenty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(euro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(euro5)
                            .addComponent(euro50)
                            .addComponent(euro20)
                            .addComponent(euro10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finish))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(chargefield, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(charge))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(euro2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(euro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fifty))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(euro5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(euro10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(twenty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(five))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(euro20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(euro50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chargefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(charge)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check)
                    .addComponent(finish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static double total= 0;
    
    
    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        
        
    }//GEN-LAST:event_sumActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        double cent5 = .05;
        total += cent5;
        Machine.stock5 ++;
    }//GEN-LAST:event_fiveActionPerformed

    private void euroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroActionPerformed
        double cent100 = 1.0;
        total += cent100;
        Machine.stock100 ++;
    }//GEN-LAST:event_euroActionPerformed

    private void euro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euro2ActionPerformed
        double cent200 = 2.0;
        total += cent200;
        Machine.stock200 ++;
    }//GEN-LAST:event_euro2ActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        double cent10 = .10;
        total += cent10;
        Machine.stock10 ++;
    }//GEN-LAST:event_tenActionPerformed

    private void fiftyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftyActionPerformed
        double cent50 = .50;
        total += cent50;
        Machine.stock50 ++;
    }//GEN-LAST:event_fiftyActionPerformed

    private void chargefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargefieldActionPerformed
        //double credit = Double.parseDouble(charge.getText());
    }//GEN-LAST:event_chargefieldActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        
        String balance = formatter.format(total);
        sum.setText(balance);
    }//GEN-LAST:event_checkActionPerformed

    private void chargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeActionPerformed
        //checks that input is a number 
        try {
     Double.parseDouble(chargefield.getText());
     total += Double.parseDouble(chargefield.getText());
        }
        catch (NumberFormatException e) {

        }
        
        
    }//GEN-LAST:event_chargeActionPerformed

    private void twentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyActionPerformed
        double cent20 = .20;
        total += cent20;
        Machine.stock20 ++;
    }//GEN-LAST:event_twentyActionPerformed

    private void euro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euro5ActionPerformed
        double cent500 = 5.0;
        total += cent500;
        Machine.stockfiver  ++;
    }//GEN-LAST:event_euro5ActionPerformed

    private void euro10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euro10ActionPerformed
        double cent1000 = 10.0;
        total += cent1000;
        Machine.stocktenner ++;
        
    }//GEN-LAST:event_euro10ActionPerformed

    private void euro20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euro20ActionPerformed
        double cent2000 = 20.0;
        total += cent2000;
        
        Machine.stocktwenty ++;
    }//GEN-LAST:event_euro20ActionPerformed

    private void euro50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euro50ActionPerformed
        double cent5000 = 50.0;
        total += cent5000;
        Machine.stockfifty ++;
    }//GEN-LAST:event_euro50ActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed

        this.dispose();
    }//GEN-LAST:event_finishActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        String balance = formatter.format(total);
        sum.setText(balance);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton charge;
    private javax.swing.JTextField chargefield;
    private javax.swing.JButton check;
    private javax.swing.JButton euro;
    private javax.swing.JButton euro10;
    private javax.swing.JButton euro2;
    private javax.swing.JButton euro20;
    private javax.swing.JButton euro5;
    private javax.swing.JButton euro50;
    private javax.swing.JButton fifty;
    private javax.swing.JButton finish;
    private javax.swing.JButton five;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField sum;
    private javax.swing.JButton ten;
    private javax.swing.JButton twenty;
    // End of variables declaration//GEN-END:variables
}
