
import com.oracle.jrockit.jfr.DataType;
import java.text.DecimalFormat;
import javax.swing.JTextField;
import java.io.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aodhan
 */
public class Machine extends javax.swing.JFrame {

    /**
     * Creates new form Machine
     */
    public Machine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        coke = new javax.swing.JRadioButton();
        pepsi = new javax.swing.JRadioButton();
        tayto = new javax.swing.JRadioButton();
        doritos = new javax.swing.JRadioButton();
        buy = new javax.swing.JButton();
        depositbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deposited = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        balancebutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        purchase = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        changefield = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));

        buttonGroup1.add(coke);
        coke.setText("Coke");
        coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeActionPerformed(evt);
            }
        });

        buttonGroup1.add(pepsi);
        pepsi.setText("Pepsi");

        buttonGroup1.add(tayto);
        tayto.setText("Tayto");

        buttonGroup1.add(doritos);
        doritos.setText("Doritos");

        buy.setText("Buy");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        depositbutton.setText("Deposit Money");
        depositbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositbuttonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment/f6e351f0255cc43be02a06faf16582cd.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment/pepsi.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment/tayto.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment/doritos.jpg"))); // NOI18N

        jLabel6.setText("Amount Deposited");

        deposited.setEditable(false);
        deposited.setText("0.00");
        deposited.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositedActionPerformed(evt);
            }
        });

        jButton1.setText("Stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finish and get change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("1.20");

        jLabel7.setText("1.00");

        jLabel8.setText("1.00");

        jLabel9.setText("1.50");

        balancebutton.setText("Check Balance");
        balancebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancebuttonActionPerformed(evt);
            }
        });

        jLabel10.setText("Your purchase");

        purchase.setEditable(false);
        purchase.setText("Nothing yet");

        jLabel11.setText("Your Change");

        changefield.setEditable(false);
        changefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changefieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pepsi)
                    .addComponent(coke)
                    .addComponent(tayto)
                    .addComponent(doritos))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel6)
                                    .addGap(11, 11, 11)
                                    .addComponent(deposited, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(buy)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(purchase)
                                    .addComponent(changefield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jButton1)
                            .addGap(78, 78, 78)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(depositbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balancebutton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coke)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pepsi)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tayto)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doritos)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositbutton)
                    .addComponent(balancebutton))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(deposited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(changefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*declaring stock variables and assigning them an initial value*/
    public static int cokeStock = 5;
    public static int pepsiStock = 5;
    public static int taytoStock = 5;
    public static int doritosStock = 5;
    
    /*declaring coin variables and assigning them an initial value*/

    public static int stock5 = 2;
    public static int stock10 = 2;
    public static int stock20 = 2;
    public static int stock50 = 2;
    public static int stock100 = 2;
    public static int stock200 = 2;
    public static int stockfiver = 2;
    public static int stocktenner = 2;
    public static int stocktwenty = 2;
    public static int stockfifty = 2;
    
    int[] stockcoin = {stockfifty, stocktwenty, stocktenner, stockfiver, stock200, stock100, stock50, stock20, stock10, stock5 };
    
    /*declaring price variables and assigning them an initial value*/

    public static double cokePrice = 1.2;
    public static double pepsiPrice = 1.0;
    public static double taytoPrice = 1.0;
    public static double doritosPrice = 1.5;
    
    /*declaring purchased variables and assigning them an initial value*/

    int cokebought = 0;
    int pepsibought = 0;
    int taytobought = 0;
    int doritosbought = 0;
    
    /*declaring a total variable and assigning it the value of 0*/

    double total = 0;
    
            int fifties  = 0;
            int twenties = 0;
            int tens = 0;
            int fivers = 0;
            int twos = 0;
            int ones = 0;
            int fiftycents = 0;
            int twentycents = 0;
            int tencents = 0;
            int fivecents = 0;
            
    double receiptchange = total;

            
    
    
    private void depositbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositbuttonActionPerformed
       Deposit depo = new Deposit();
       depo.setVisible(true);
    }//GEN-LAST:event_depositbuttonActionPerformed

    private void depositedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositedActionPerformed
        
    }//GEN-LAST:event_depositedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StockForm stockf = new StockForm();
        stockf.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void balancebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancebuttonActionPerformed
        //String balance = String.valueOf(Deposit.total);
        DecimalFormat formatter = new DecimalFormat("#0.00");
        String balance = formatter.format(Deposit.total);
        deposited.setText(balance);
        deposited.setVisible(true);
       

        
    }//GEN-LAST:event_balancebuttonActionPerformed

    private void cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cokeActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        if(coke.isSelected()){
            if(cokeStock > 0){
               
                
                if(cokePrice <= Deposit.total){
                    
                    Deposit.total -= cokePrice;
                    cokeStock--;
                    purchase.setText("Coke");
                    cokebought ++;


                }else{
                    purchase.setText("Coke costs too much");
                }
            }else{
                purchase.setText("Coke is out of stock");
            }
        }else if(pepsi.isSelected()){
            if(pepsiStock > 0){
               
                
                if(pepsiPrice <= Deposit.total){
                    
                    Deposit.total -= pepsiPrice;
                    pepsiStock--;
                    purchase.setText("Pepsi");
                    pepsibought ++;

                }else{
                    purchase.setText("Pepsi costs too much");
                }
            }else{
                purchase.setText("Pepsi is out of stock");
            }
        }else if(tayto.isSelected()){
            if(taytoStock > 0){
               
                
                if(taytoPrice <= Deposit.total){
                    
                    Deposit.total -= taytoPrice;
                    taytoStock--;
                    purchase.setText("Tayto");
                    taytobought ++;

                }else{
                    purchase.setText("Tayto costs too much");
                }
            }else{
                purchase.setText("Tayto is out of stock");
            }
        }else if(doritos.isSelected()){
            if(doritosStock > 0){
               
                
                if(doritosPrice <= Deposit.total){
                    
                    Deposit.total -= doritosPrice;
                    doritosStock--;
                    purchase.setText("Doritos");
                    doritosbought ++;

                }else{
                    purchase.setText("Doritos costs too much");
                }
            }else{
                purchase.setText("Doritos is out of stock");
            }
        }else{
                    purchase.setText("Error in selection");

        }
        DecimalFormat formatter = new DecimalFormat("#0.00");
        String change = formatter.format(Deposit.total);

        changefield.setText(change);
        
    }//GEN-LAST:event_buyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //writes a receipt to c/test with your remaining balance and purchase list
        int[] coins = {0, 0, 0, 0, 0, 0, 0, 0,0, 0};
            double[] coinvalue = {50,20,10,5,2,1,0.5,0.2,0.1,0.05};
            
                    String money = "";

            
        for(int i = 0; i < coins.length; i++){
                  
                if(receiptchange >= coinvalue[i]){
                    coins[i] ++;
                    stockfifty--;
                    receiptchange = receiptchange - coinvalue[i];
                    money += coins[i] + coinvalue[i] ;
                    
                }}
        try {
            FileWriter outFile = new FileWriter("C:/test/myfile.txt");
            PrintWriter out = new PrintWriter(outFile);
          
            DecimalFormat formatter = new DecimalFormat("#0.00");
            String change = formatter.format(Deposit.total);
            
            
            

                    
            
                out.println(money);
                /*else if(receiptchange >= 20 && stocktwenty > 0){
                    twenties ++;
                    stocktwenty--;
                    receiptchange = receiptchange -20;
                }else if(receiptchange >= 10 && stocktenner > 0){
                    tens ++;
                    stocktenner--;
                    receiptchange -= 10;
                }else if(receiptchange >= 5 && stockfiver> 0){
                    fivers ++;
                    stockfiver--;
                    receiptchange -= 5;
                }else if(receiptchange >= 2 && stock200 > 0){
                    twos ++;
                    stock200--;
                    receiptchange -= 2;
                }else if(receiptchange >= 1 && stock100 > 0){
                    ones ++;
                    stock100--;
                    receiptchange -= 1;
                }else if(receiptchange >= .50 && stock50 > 0){
                    fiftycents ++;
                    stock50--;
                    receiptchange -= .50;
                }else if(receiptchange >= .20 && stock20 > 0){
                    twentycents ++;
                    stock20--;
                    receiptchange = receiptchange - .20;
                }else if(receiptchange > .10 && stock10 > 0){
                    tencents ++;
                    stock10--;
                    receiptchange = receiptchange - .1;
                }else if(receiptchange > .05 && stock5 > 0){
                    fivecents ++;
                    stock5--;
                    receiptchange = receiptchange - .05;
                    }
            }*/
            
           
     
            out.println("You will receive receipt " +receiptchange );
            
            // Write text to file
            out.println("You bought: "+ cokebought+ " Coke " + pepsibought+ " Pepsi "+ taytobought+ " Tayto " + doritosbought+ " Doritos " );

            out.println("Your total change is "+ change);
            

            out.println("Thanks for shopping with us!");
            out.close();
       } catch (IOException e){
            e.printStackTrace();
       }

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void changefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Machine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balancebutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buy;
    private javax.swing.JTextField changefield;
    private javax.swing.JRadioButton coke;
    private javax.swing.JButton depositbutton;
    private javax.swing.JTextField deposited;
    private javax.swing.JRadioButton doritos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton pepsi;
    private javax.swing.JTextField purchase;
    private javax.swing.JRadioButton tayto;
    // End of variables declaration//GEN-END:variables
}
